# Generated by Django 5.1.7 on 2025-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/'),
        ),
    ]
